version: '3.8'

services:
  auto-disclaimer:
    build: .
    container_name: auto-disclaimer-adder
    ports:
      - "7860:7860"  # Updated port to match the Gradio app port
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
      - ./output:/app/output  # Added output directory for processed videos
    environment:
      - PYTHONUNBUFFERED=1
    # GPU configuration - comment out if not using NVIDIA GPU
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '2gb'  # Reduced shared memory size for better compatibility
    restart: unless-stopped
    ulimits:
      memlock: -1  # Unlimited memory lock
      stack: 67108864  # 64MB stack size 